<%= file = File.join(RAILS_ROOT, "config", "connect.yml")
    IO.read(file) %>

test:
  <<: *local
  database: test_app_edge
  
development:
  <<: *local
  database: test_app_edge
  
production:
  <<: *local
  database: test_app_edge
